# Use a compatible Python version
FROM python:3.10-slim
# Set work directory
WORKDIR /app
# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    python3-dev \
    musl-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
# Ensure pip is up-to-date
RUN pip install --upgrade pip==25.0.1
# Cache dependencies
COPY requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Copy app code
COPY . .
EXPOSE 8084
# Run the log processor
CMD ["python", "main.py"]